version: 2
jobs:
  build:
    docker:
      - image: golang:1-buster
    steps:
      - restore_cache:
          keys:
          - go-mod-v1-{{ checksum "go.sum" }}
      - checkout
      - run: make
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
