version: 2
jobs:
  build:
    docker:
      - image: golang:1-buster
    steps:
      - checkout
      - restore_cache:
          keys:
          - go-mod-{{ checksum "go.sum" }}
      - restore_cache:
          keys:
            - tools-{{ checksum "Makefile" }}
      - run: make
      - save_cache:
          key: go-mod-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - save_cache:
          key: tools-{{ checksum "Makefile" }}
          paths:
            - "bin"
